(function(g){var window=this;var Wya=function(a,b){return g.Vb(a,b)},d6=function(a){g.zm(a,"zx",g.Va());
return a},e6=function(a,b,c){g.xa(c)||(c=[String(c)]);
g.Cm(a.g,b,c)},Xya=function(a,b){var c=[];
g.Zi(b,function(a){try{var b=g.ZC.prototype.o.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.YC(b)&&c.push(a):c.push(a)},a);
return c},Yya=function(a,b){var c=Xya(a,b);
(0,g.G)(c,function(a){g.ZC.prototype.remove.call(this,a)},a)},Zya=function(){var a=g.SG;
Yya(a,a.g.Yd(!0))},$ya=function(a,b,c,d){var e=new g.qm(null,void 0);
a&&g.rm(e,a);b&&g.sm(e,b);c&&g.tm(e,c);d&&g.um(e,d);return e},aza=function(a){g.kG[a]&&(a=g.kG[a],(0,g.G)(a,function(a){g.iG[a]&&delete g.iG[a]}),a.length=0)},bza=function(a){var b=g.hG();
if(b)if(b.clear(a),a)aza(a);else for(var c in g.kG)aza(c)},f6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.A=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.km;this.g=this.o="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",cza(this,a.capabilities||""),dza(this,a.experiments||""),this.o=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},cza=function(a,b){a.capabilities.clear();
(0,g.Jd)(b.split(","),g.Fa(Wya,eza)).forEach(function(b){a.capabilities.add(b)})},dza=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},g6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},h6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},fza=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},gza=function(a){return new g6(a)},hza=function(a){return g.xa(a)?(0,g.H)(a,gza):[]},i6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},j6=function(a){return g.xa(a)?"["+(0,g.H)(a,i6).join(",")+"]":"null"},k6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},iza=function(a){return(0,g.H)(a,function(a){return{key:a.id,
name:a.name}})},l6=function(a,b){return g.fb(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},m6=function(a,b){return g.fb(a,function(a){return h6(a,b)})},n6=function(){var a=g.VG("yt-remote-connected-devices")||[];
g.Eb(a);return a},jza=function(a){if(g.lb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.H)(a,function(a,b){return 0==b?a:a.substring(c.length)})},kza=function(a){g.UG("yt-remote-connected-devices",a,86400)},p6=function(){if(o6)return o6;
var a=g.VG("yt-remote-device-id");a||(a=k6(),g.UG("yt-remote-device-id",a,31536E3));for(var b=n6(),c=1,d=a;g.kb(b,d);)c++,d=a+"#"+c;return o6=d},q6=function(){var a=n6(),b=p6();
g.kb(a,b);g.$G()&&g.Gb(a,b);a=jza(a);if(g.lb(a))try{g.YG.remove("remote_sid","/","youtube.com")}catch(c){}else try{g.ZG("remote_sid",a.join(","),-1)}catch(c){}},lza=function(){return g.VG("yt-remote-session-browser-channel")},mza=function(){return g.VG("yt-remote-local-screens")||[]},nza=function(){g.UG("yt-remote-lounge-token-expiration",!0,86400)},oza=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.H)(mza(),function(a){return a.loungeToken}),c=(0,g.H)(a,function(a){return a.loungeToken});
(0,g.Zl)(c,function(a){return!g.kb(b,a)})&&nza();
g.UG("yt-remote-local-screens",a,31536E3)},pza=function(a,b){g.UG("yt-remote-session-browser-channel",a);
g.UG("yt-remote-session-screen-id",b);var c=n6(),d=p6();g.kb(c,d)||c.push(d);kza(c);q6()},r6=function(a){a||(g.WG("yt-remote-session-screen-id"),g.WG("yt-remote-session-video-id"));
q6();a=n6();g.sb(a,p6());kza(a)},qza=function(){if(!s6){var a=g.eD();
a&&(s6=new g.TC(a))}return s6?!!s6.get("yt-remote-use-staging-server"):!1},rza=function(){var a=window.document.createElement("a");
g.Xc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Za(a)},sza=function(a,b){var c=g.Bd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.Yc(c,g.ae("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},tza=function(){var a=rza(),b=window.document.getElementById(a),c=b&&g.xF(b,"loaded");
c||b&&!c||(b=sza(a,function(){g.xF(b,"loaded")||(g.wF(b,"loaded","true"),g.oG(a),g.vE(g.Fa(bza,a),0))}))},uza=function(){var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);
return a?(0,window.parseInt)(a[1],10):0},t6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},vza=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},wza=function(a,b){var c=new window.XMLHttpRequest;
c.onreadystatechange=function(){4==c.readyState&&200==c.status&&b(!0)};
c.onerror=function(){b(!1)};
try{c.open("GET",a,!0),c.send()}catch(d){b(!1)}},x6=function(a){if(a>=xza.length)u6();
else{var b=xza[a],c="chrome-extension://"+b+yza;0<=v6.indexOf(b)?wza(c,function(d){d?(window.chrome.cast=window.chrome.cast||{},window.chrome.cast.extensionId=b,w6(c,u6)):x6(a+1)}):w6(c,function(){x6(a+1)})}},w6=function(a,b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},y6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},u6=function(){var a=vza();
a&&a(!1,"No cast extension found")},Aza=function(){if(zza){var a=2,b=vza(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;w6("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",u6,c)}},Bza=function(){if(y6("CriOS")){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
if(a){Aza();a({command:"cast.sender.init"});return}}if(!window.chrome||y6("Edge"))u6();else if(Aza(),y6("Android")&&y6("Chrome/")&&window.navigator.presentation){a="";var b=uza();55<=b?a="55":50<=b&&(a="50");w6("//www.gstatic.com/eureka/clank"+a+yza,u6)}else x6(0)},z6=function(a,b,c){g.L.call(this);
this.D=null!=c?(0,g.z)(a,c):a;this.sc=b;this.C=(0,g.z)(this.MH,this);this.g=!1;this.o=0;this.A=this.Aa=null;this.B=[]},A6=function(a,b){this.g=a;
this.o=b},B6=function(a,b,c,d,e){this.g=a;
this.A=c;this.G=d;this.F=e||1;this.C=45E3;this.B=new g.Gm(this);this.o=new g.qg;this.o.setInterval(250)},Dza=function(a,b,c){a.nj=1;
a.nh=d6(b.clone());a.Hi=c;a.D=!0;Cza(a,null)},C6=function(a,b,c,d,e){a.nj=1;
a.nh=d6(b.clone());a.Hi=null;a.D=c;e&&(a.eC=!1);Cza(a,d)},Cza=function(a,b){a.Ll=(0,g.F)();
D6(a);a.Eh=a.nh.clone();e6(a.Eh,"t",a.F);a.Tl=0;a.Nc=a.g.zq(a.g.Nl()?b:null);0<a.gr&&(a.Mo=new g.Nk((0,g.z)(a.mD,a,a.Nc),a.gr));a.B.V(a.Nc,"readystatechange",a.ES);var c=a.gi?g.ac(a.gi):{};a.Hi?(a.vp="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Nc.send(a.Eh,a.vp,a.Hi,c)):(a.vp="GET",a.eC&&!g.xd&&(c.Connection="close"),a.Nc.send(a.Eh,a.vp,null,c));a.g.qf(1)},Gza=function(a,b,c){for(var d=!0;!a.Qh&&a.Tl<c.length;){var e=Eza(a,c);
if(e==E6){4==b&&(a.hi=4,F6(),d=!1);break}else if(e==Fza){a.hi=4;F6();d=!1;break}else G6(a,e)}4==b&&0==c.length&&(a.hi=1,F6(),d=!1);a.uf=a.uf&&d;d||(H6(a),I6(a))},Eza=function(a,b){var c=a.Tl,d=b.indexOf("\n",c);
if(-1==d)return E6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return Fza;d+=1;if(d+c>b.length)return E6;var e=b.substr(d,c);a.Tl=d+c;return e},Iza=function(a,b){a.Ll=(0,g.F)();
D6(a);var c=b?window.location.hostname:"";a.Eh=a.nh.clone();g.zm(a.Eh,"DOMAIN",c);g.zm(a.Eh,"t",a.F);try{a.vf=new window.ActiveXObject("htmlfile")}catch(n){H6(a);a.hi=7;F6();I6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in J6)k=J6[l];else if(l in Hza)k=J6[l]=Hza[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
J6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.Zc(g.vc("b/12014412"),d);a.vf.open();a.vf.write(g.Rc(c));a.vf.close();a.vf.parentWindow.m=(0,g.z)(a.IR,a);a.vf.parentWindow.d=(0,g.z)(a.xB,a,!0);a.vf.parentWindow.rpcClose=(0,g.z)(a.xB,a,!1);c=a.vf.createElement("DIV");a.vf.parentWindow.document.body.appendChild(c);d=g.Hc(a.Eh.toString());d=g.Oa(g.Ec(d));d=g.Zc(g.vc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.Rc(d);a.g.qf(1)},D6=function(a){a.Eu=
(0,g.F)()+a.C;
Jza(a,a.C)},Jza=function(a,b){if(null!=a.pk)throw Error("WatchDog timer not null");
a.pk=K6((0,g.z)(a.ZR,a),b)},L6=function(a){a.pk&&(g.w.clearTimeout(a.pk),a.pk=null)},I6=function(a){a.g.Ix()||a.Qh||a.g.Do(a)},H6=function(a){L6(a);
g.We(a.Mo);a.Mo=null;a.o.stop();g.Mm(a.B);if(a.Nc){var b=a.Nc;a.Nc=null;b.abort();b.dispose()}a.vf&&(a.vf=null)},G6=function(a,b){try{a.g.qB(a,b),a.g.qf(4)}catch(c){}},Lza=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;Kza(a,b,function(e){e?c(!0):g.w.setTimeout(function(){Lza(a,b,c,d,f)},f)})}},Kza=function(a,b,c){var d=new window.Image;
d.onload=function(){try{M6(d),c(!0)}catch(e){}};
d.onerror=function(){try{M6(d),c(!1)}catch(e){}};
d.onabort=function(){try{M6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{M6(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},M6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},Mza=function(a){this.g=a;
this.o=new A6},Nza=function(a){var b=N6(a.g,a.tk,"/mail/images/cleardot.gif");
d6(b);Lza(b.toString(),5E3,(0,g.z)(a.VG,a),3,2E3);a.qf(1)},P6=function(a){var b=a.g.J;
if(null!=b)F6(),b?(F6(),O6(a.g,a,!1)):(F6(),O6(a.g,a,!0));else if(a.pe=new B6(a,0,void 0,void 0,void 0),a.pe.gi=a.ar,b=a.g,b=N6(b,b.Nl()?a.Uk:null,a.fr),F6(),!g.vd||g.rc(10))e6(b,"TYPE","xmlhttp"),C6(a.pe,b,!1,a.Uk,!1);else{e6(b,"TYPE","html");var c=a.pe;a=!!a.Uk;c.nj=3;c.nh=d6(b.clone());Iza(c,a)}},Q6=function(a,b,c,d){this.G=a||null;
this.g=1;this.o=[];this.B=[];this.C=new A6;this.I=b||null;this.J=null!=c?c:null;this.D=d||!1},Oza=function(a,b){this.g=a;
this.map=b;this.context=null},Pza=function(a){g.Ye.call(this,"statevent",a)},Qza=function(a,b){g.Ye.call(this,"timingevent",a);
this.size=b},Rza=function(a){g.Ye.call(this,"serverreachability",a)},Uza=function(a){Sza(a);
if(3==a.g){var b=a.Cl++,c=a.xn.clone();g.zm(c,"SID",a.A);g.zm(c,"RID",b);g.zm(c,"TYPE","terminate");R6(a,c);b=new B6(a,0,a.A,b,void 0);b.nj=2;b.nh=d6(c.clone());(new window.Image).src=b.nh;b.Ll=(0,g.F)();D6(b)}Tza(a)},Vza=function(a){a.sH(1,0);
a.xn=N6(a,null,a.Zq);S6(a)},Sza=function(a){a.bh&&(a.bh.abort(),a.bh=null);
a.oc&&(a.oc.cancel(),a.oc=null);a.qg&&(g.w.clearTimeout(a.qg),a.qg=null);T6(a);a.Od&&(a.Od.cancel(),a.Od=null);a.eh&&(g.w.clearTimeout(a.eh),a.eh=null)},Wza=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.o.push(new Oza(a.IN++,b));2!=a.g&&3!=a.g||S6(a)},S6=function(a){a.Od||a.eh||(a.eh=K6((0,g.z)(a.vB,a),0),a.Jk=0)},Yza=function(a,b){if(1==a.g){if(!b){a.Cl=Math.floor(1E5*Math.random());
var c=a.Cl++,d=new B6(a,0,"",c,void 0);d.gi=null;var e=U6(a),f=a.xn.clone();g.zm(f,"RID",c);a.G&&g.zm(f,"CVER",a.G);R6(a,f);Dza(d,f,e);a.Od=d;a.g=2}}else 3==a.g&&(b?Xza(a,b):0==a.o.length||a.Od||Xza(a))},Xza=function(a,b){if(b)if(6<a.Sh){a.o=a.B.concat(a.o);
a.B.length=0;var c=a.Cl-1;var d=U6(a)}else c=b.G,d=b.Hi;else c=a.Cl++,d=U6(a);var e=a.xn.clone();g.zm(e,"SID",a.A);g.zm(e,"RID",c);g.zm(e,"AID",a.Bj);R6(a,e);c=new B6(a,0,a.A,c,a.Jk+1);c.gi=null;c.setTimeout(Math.round(1E4)+Math.round(1E4*Math.random()));a.Od=c;Dza(c,e,d)},R6=function(a,b){if(a.qd){var c=a.qd.lx(a);
c&&g.Lb(c,function(a,c){g.zm(b,c,a)})}},U6=function(a){var b=Math.min(a.o.length,1E3),c=["count="+b];
if(6<a.Sh&&0<b){var d=a.o[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.o[e].g,k=a.o[e].map;f=6>=a.Sh?e:f-d;try{g.Lb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.B=a.B.concat(a.o.splice(0,b));
return c.join("&")},Zza=function(a){a.oc||a.qg||(a.F=1,a.qg=K6((0,g.z)(a.uB,a),0),a.Xi=0)},V6=function(a){if(a.oc||a.qg||3<=a.Xi)return!1;
a.F++;a.qg=K6((0,g.z)(a.uB,a),$za(a,a.Xi));a.Xi++;return!0},O6=function(a,b,c){a.up=c;
a.cf=b.xg;a.D||Vza(a)},T6=function(a){null!=a.Uh&&(g.w.clearTimeout(a.Uh),a.Uh=null)},$za=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},W6=function(a,b){if(2==b||9==b){var c=null;
a.qd&&(c=null);var d=(0,g.z)(a.wT,a);c||(c=new g.qm("//www.google.com/images/cleardot.gif"),d6(c));Kza(c.toString(),1E4,d)}else F6();aAa(a,b)},aAa=function(a,b){a.g=0;
a.qd&&a.qd.jw(a,b);Tza(a);Sza(a)},Tza=function(a){a.g=0;
a.cf=-1;if(a.qd)if(0==a.B.length&&0==a.o.length)a.qd.nq(a);else{var b=g.vb(a.B),c=g.vb(a.o);a.B.length=0;a.o.length=0;a.qd.nq(a,b,c)}},N6=function(a,b,c){var d=g.Am(c);
if(""!=d.o)b&&g.sm(d,b+"."+d.o),g.tm(d,d.C);else{var e=window.location;d=$ya(e.protocol,b?b+"."+e.hostname:e.hostname,e.port,c)}a.Gk&&g.Lb(a.Gk,function(a,b){g.zm(d,b,a)});
g.zm(d,"VER",a.Sh);R6(a,d);return d},K6=function(a,b){if(!g.za(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},F6=function(){X6.dispatchEvent(new Pza(X6))},bAa=function(){},cAa=function(a,b){this.action=a;
this.params=b||{}},Z6=function(a,b){g.L.call(this);
this.g=new g.Xt(this.A,0,this);g.M(this,this.g);this.o=this.sc=0;if(g.za(a))b&&(a=(0,g.z)(a,b));else if(a&&g.za(a.handleEvent))a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a;Y6(this)},Y6=function(a){a.g.stop();
a.sc=5E3+2E4*Math.random()},$6=function(a,b,c){this.L=a;
this.D=b;this.A=new g.SC;this.o=new Z6(this.aU,this);this.g=this.bb=null;this.J=!1;this.C=null;this.I="";this.G=this.B=0;this.F=[];this.N=c||!1},dAa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.up,sessionId:a.g.A,arrayId:a.g.Bj}},eAa=function(a,b){a.G=b||0;
a.o.stop();a.g&&(3==a.g.g&&Yza(a.g),Uza(a.g));a.G=0},a7=function(a){return!!a.g&&3==a.g.g},fAa=function(a,b){(a.D.loungeIdToken=b)||a.o.stop()},b7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.o=!0;a=a||window.document.location.href;var b=g.Gg(a)||"";b&&(this.port=":"+b);this.domain=g.Fg(a)||"";a=g.Ib;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ya(a,"10.0")&&(this.o=!1))},c7=function(a,b){var c=a.g;
if(g.t(void 0)?0:a.o)c="https://"+a.domain+a.port+a.g;return g.Pg(c+b,{})},d7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,Ib:g.Fa(a.B,d,!0),onError:g.Fa(a.A,e),td:g.Fa(a.C,e)};c&&(a.Pb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.LE(b,a)},jAa=function(){var a=gAa;
hAa();e7.push(a);iAa(e7)},f7=function(a,b){hAa();
var c=e7,d=kAa(a,String(b));g.lb(c)?lAa(d):(iAa(c),(0,g.G)(c,function(a){a(d)}))},hAa=function(){e7||(e7=g.x("yt.mdx.remote.debug.handlers_")||[],g.ua("yt.mdx.remote.debug.handlers_",e7,void 0))},lAa=function(a){var b=(g7+1)%50;
g7=b;h7[b]=a;i7||(i7=49==b)},iAa=function(a){var b=h7;
if(b[0]){var c=g7,d=i7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.G)(a,function(a){a(e)})}while(d!=c);
h7=Array(50);g7=-1;i7=!1}},kAa=function(a,b){var c=((0,g.F)()-mAa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},j7=function(a){g.ZF.call(this);
this.F=a;this.g=[]},nAa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},oAa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Jd)(a.g,function(a){return!!l6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=nAa(a,b[d])||c;return c},pAa=function(a,b){var c=a.g.length;
a.g=(0,g.Jd)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},k7=function(a,b,c,d){g.ZF.call(this);
this.D=a;this.C=b;this.A=c;this.B=d;this.o=0;this.g=null;this.Aa=window.NaN},m7=function(a){j7.call(this,"LocalScreenService");
this.A=a;this.o=window.NaN;l7(this);this.info("Initializing with "+j6(this.g))},qAa=function(a){if(a.g.length){var b=(0,g.H)(a.g,function(a){return a.id}),c=c7(a.A,"/pairing/get_lounge_token_batch");
d7(a.A,c,{screen_ids:b.join(",")},(0,g.z)(a.YH,a),(0,g.z)(a.XH,a))}},l7=function(a){var b=hza(mza());
b=(0,g.Jd)(b,function(a){return!a.uuid});
return oAa(a,b)},n7=function(a,b){oza((0,g.H)(a.g,fza));
b&&nza()},p7=function(a,b){g.ZF.call(this);
this.D=b;var c=g.VG("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.D(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.kb(c,l)}this.g=d;this.C=a;this.A=this.B=window.NaN;this.o=null;o7("Initialized with "+g.xg(this.g))},rAa=function(a,b,c){var d=c7(a.C,"/pairing/get_screen_availability");
d7(a.C,d,{lounge_token:b.token},(0,g.z)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},q7=function(a,b){a:if(g.Qb(b)!=g.Qb(a.g))var c=!1;
else{c=g.Sb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(o7("Updated online screens: "+g.xg(a.g)),a.g=b,a.U("screenChange"));sAa(a)},r7=function(a){(0,window.isNaN)(a.A)||g.xE(a.A);
a.A=g.vE((0,g.z)(a.Ot,a),0<a.B&&a.B<(0,g.F)()?2E4:1E4)},o7=function(a){f7("OnlineScreenService",a)},tAa=function(a){var b={};
(0,g.G)(a.D(),function(a){a.token?b[a.token]=a.id:this.ac("Requesting availability of screen w/o lounge token.")});
return b},sAa=function(a){a=g.Sb(g.Mb(a.g,function(a){return a}));
g.Eb(a);a.length?g.UG("yt-remote-online-screen-ids",a.join(","),60):g.WG("yt-remote-online-screen-ids")},s7=function(a){j7.call(this,"ScreenService");
this.D=a;this.o=this.A=null;this.B=[];this.C={};uAa(this)},wAa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.C[b]);var k=a.ge();if(k=(c?m6(k,c):null)||m6(k,b)){k.uuid=b;var l=t7(a,k);rAa(a.o,l,function(a){e(a?l:null)})}else c?vAa(a,c,(0,g.z)(function(a){var f=t7(this,new g6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));rAa(this.o,f,function(a){e(a?f:null)})},a),f):e(null)},xAa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},vAa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Pb:{screen_ids:b},method:"POST",context:a,Ib:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.LE(c7(a.D,"/pairing/get_lounge_token_batch"),e)},yAa=function(a){a.g=a.A.ge();
var b=a.C,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+j6(a.g))},uAa=function(a){u7(a);
a.A=new m7(a.D);a.A.subscribe("screenChange",(0,g.z)(a.kI,a));yAa(a);a.B=hza(g.VG("yt-remote-automatic-screen-cache")||[]);u7(a);a.info("Initializing automatic screens: "+j6(a.B));a.o=new p7(a.D,(0,g.z)(a.ge,a,!0));a.o.subscribe("screenChange",(0,g.z)(function(){this.U("onlineScreenChange")},a))},t7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=m6(a.B,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.B.push(b),g.UG("yt-remote-automatic-screen-cache",(0,g.H)(a.B,fza)));u7(a);a.C[b.uuid]=b.id;g.UG("yt-remote-device-id-map",a.C,31536E3);return b},u7=function(a){a.C=g.VG("yt-remote-device-id-map")||{}},v7=function(a,b,c){g.ZF.call(this);
this.N=c;this.I=a;this.o=b;this.A=null},w7=function(a,b){f7(a.N,b)},x7=function(a,b){v7.call(this,a,b,"CastSession");
this.g=null;this.B=0;this.D=(0,g.z)(this.gU,this);this.C=(0,g.z)(this.jS,this);this.B=g.vE((0,g.z)(function(){zAa(this,null)},this),12E4)},AAa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.xg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.y,(0,g.z)(function(){w7(this,"Failed to send message: getMdxSessionStatus.")},a)):w7(a,"Sending yt message without session: "+g.xg(b))},zAa=function(a,b){g.xE(a.B);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.A||a.A.id!=b){var c=(0,g.z)(a.Eo,a),d=(0,g.z)(a.ne,a);a.Bx(b,c,d,5)}}else a.ne(Error("Waiting for session status timed out."))},y7=function(a,b,c){v7.call(this,a,b,"DialSession");
this.B=this.G=null;this.J="";this.O=c;this.C=null;this.F=g.y;this.D=window.NaN;this.L=(0,g.z)(this.jU,this);this.g=g.y},BAa=function(a){a.g=a.I.sD(a.J,a.o.label,a.o.friendlyName,(0,g.z)(function(a){this.g=g.y;
this.Eo(a)},a),(0,g.z)(function(a){this.g=g.y;
this.ne(a)},a))},CAa=function(a){var b={};
b.pairingCode=a.J;b.theme=a.O;if(a.C){var c=a.C.currentTime||0;b.v=a.C.videoId;b.t=c}qza()&&(b.env_useStageMdx=1);return g.Ng(b)},z7=function(a,b){v7.call(this,a,b,"ManualSession");
this.g=g.vE((0,g.z)(this.Cj,this,null),150)},A7=function(a,b,c,d){g.ZF.call(this);
this.o=a;this.F=b||"233637DE";this.D=c||"cl";this.G=d||!1;this.g=null;this.C=!1;this.A=[];this.B=(0,g.z)(this.OQ,this)},DAa=function(a,b){return b?g.fb(a.A,function(a){return h6(b,a.label)},a):null},B7=function(a){f7("Controller",a)},gAa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},C7=function(a){return a.C||!!a.A.length||!!a.g},D7=function(a,b,c){b!=a.g&&(g.We(a.g),(a.g=b)?(c?a.U("yt-remote-cast2-receiver-resumed",b.o):a.U("yt-remote-cast2-receiver-selected",
b.o),b.subscribe("sessionScreen",(0,g.z)(a.sB,a,b)),b.A?a.U("yt-remote-cast2-session-change",b.A):c&&a.g.Cj(null)):a.U("yt-remote-cast2-session-change",null))},EAa=function(a){var b=a.o.rD(),c=a.g&&a.g.o;
a=(0,g.H)(b,function(a){c&&h6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=DAa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},JAa=function(a,b,c,d,e,f,k){FAa()?GAa(b,e,f,k)&&(F7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?HAa(a,c):(window.__onGCastApiAvailable=function(b,d){b?HAa(a,c):(G7("Failed to load cast API: "+d),H7(!1),F7(!1),g.WG("yt-remote-cast-available"),g.WG("yt-remote-cast-receiver"),IAa(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):tza():Bza())):E7("Cannot initialize because not running Chrome")},IAa=function(){E7("dispose");
var a=I7();a&&a.dispose();g.ua("yt.mdx.remote.cloudview.instance_",null,void 0);KAa(!1);g.mG(J7);J7.length=0},K7=function(){return!!g.VG("yt-remote-cast-installed")},LAa=function(){var a=g.VG("yt-remote-cast-receiver");
return a?a.friendlyName:null},MAa=function(){E7("clearCurrentReceiver");
g.WG("yt-remote-cast-receiver")},NAa=function(){return K7()?I7()?I7().getCastSession():(G7("getCastSelector: Cast is not initialized."),null):(G7("getCastSelector: Cast API is not installed!"),null)},M7=function(){K7()?I7()?L7()?(E7("Requesting cast selector."),I7().requestSession()):(E7("Wait for cast API to be ready to request the session."),J7.push(g.lG("yt-remote-cast2-api-ready",M7))):G7("requestCastSelector: Cast is not initialized."):G7("requestCastSelector: Cast API is not installed!")},N7=
function(a,b){L7()?I7().setConnectedScreenStatus(a,b):G7("setConnectedScreenStatus called before ready.")},FAa=function(){var a=0<=g.Ib.search(/ (CrMo|Chrome|CriOS)\//);
return g.GJ||a},OAa=function(a,b){I7().init(a,b)},GAa=function(a,b,c,d){var e=!1;
I7()||(a=new A7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.UG("yt-remote-cast-available",a);g.pG("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){E7("onReceiverSelected: "+a.friendlyName);
g.UG("yt-remote-cast-receiver",a);g.pG("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){E7("onReceiverResumed: "+a.friendlyName);
g.UG("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){E7("onSessionChange: "+i6(a));
a||g.WG("yt-remote-cast-receiver");g.pG("yt-remote-cast2-session-change",a)}),g.ua("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
E7("cloudview.createSingleton_: "+e);return e},I7=function(){return g.x("yt.mdx.remote.cloudview.instance_")},HAa=function(a,b){H7(!0);
F7(!1);OAa(a,function(a){a?(KAa(!0),g.oG("yt-remote-cast2-api-ready")):(G7("Failed to initialize cast API."),H7(!1),g.WG("yt-remote-cast-available"),g.WG("yt-remote-cast-receiver"),IAa());b(a)})},E7=function(a){f7("cloudview",a)},G7=function(a){f7("cloudview",a)},H7=function(a){E7("setCastInstalled_ "+a);
g.UG("yt-remote-cast-installed",a)},L7=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},KAa=function(a){E7("setApiReady_ "+a);
g.ua("yt.mdx.remote.cloudview.apiReady_",a,void 0)},F7=function(a){g.ua("yt.mdx.remote.cloudview.initializing_",a,void 0)},O7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.o=null;this.hasNext=this.Kf=!1;this.J=this.I=this.A=this.C=0;this.B=window.NaN;this.D=!1;this.reset(a)},P7=function(a){a.audioTrackId=null;
a.o=null;a.g=-1;a.Kf=!1;a.hasNext=!1;a.G=0;a.F=(0,g.F)();a.C=0;a.A=0;a.I=0;a.J=0;a.B=window.NaN;a.D=!1},Q7=function(a){return a.kb()?((0,g.F)()-a.F)/1E3:0},R7=function(a,b){a.G=b;
a.F=(0,g.F)()},S7=function(a){switch(a.g){case 1:case 1081:return((0,g.F)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},T7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&P7(a)},U7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.bc(a.o);b.hasPrevious=a.Kf;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.C;b.seekableEnd=a.A;b.duration=a.I;b.loadedTime=a.J;b.liveIngestionTime=a.B;return b},W7=function(a,b){g.ZF.call(this);
this.g=0;this.B=a;this.D=[];this.C=new g.iC;this.A=this.o=null;this.I=(0,g.z)(this.sO,this);this.F=(0,g.z)(this.El,this);this.G=(0,g.z)(this.rO,this);this.J=(0,g.z)(this.FO,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Ku,this),PAa(this))):c=3;0!=c&&(b?this.Ku(c):g.vE((0,g.z)(function(){this.Ku(c)},this),0));
var d=NAa();d&&V7(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},X7=function(a){return new O7(a.B.getPlayerContextData())},PAa=function(a){(0,g.G)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.D.push(this.B.subscribe(a,g.Fa(this.KQ,a),this))},a)},QAa=function(a){(0,g.G)(a.D,function(a){this.B.unsubscribeByKey(a)},a);
a.D.length=0},Y7=function(a,b){50>a.C.Jc()&&g.kC(a.C,b)},$7=function(a,b,c){var d=X7(a);
R7(d,c);-1E3!=d.g&&(d.g=b);Z7(a,d)},a8=function(a,b,c){a.B.sendMessage(b,c)},Z7=function(a,b){QAa(a);
a.B.setPlayerContextData(U7(b));PAa(a)},V7=function(a,b){a.A&&(a.A.removeUpdateListener(a.I),a.A.removeMediaListener(a.F),a.El(null));
a.A=b;a.A&&(b8("Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.I),a.A.addMediaListener(a.F),a.A.media.length&&a.El(a.A.media[0]))},RAa=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=X7(a);b.contentId!=d.videoId&&b8("Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;R7(d,a.o.getEstimatedTime());Z7(a,d)}else b8("No cast media video. Ignoring state update.")},b8=function(a){f7("CP",a)},c8=function(a,b,c){return(0,g.z)(function(a){this.ac("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.ac("Retrying "+b+" using MDx browser channel."),a8(this,b,c))},a)},d8=function(a,b,c){g.ZF.call(this);
this.C=window.NaN;this.O=!1;this.J=this.I=this.L=this.N=window.NaN;this.T=[];this.B=this.F=this.A=this.fb=this.g=null;this.oa=a;this.T.push(g.KF(window,"beforeunload",(0,g.z)(this.PH,this)));this.o=[];this.fb=new O7;this.Z=b.id;this.g=SAa(this,c);this.g.subscribe("handlerOpened",this.wO,this);this.g.subscribe("handlerClosed",this.tO,this);this.g.subscribe("handlerError",this.uO,this);this.g.subscribe("handlerMessage",this.vO,this);fAa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.fb.videoId;g.$G()&&g.UG("yt-remote-session-video-id",a)},this)},e8=function(a){f7("conn",a)},SAa=function(a,b){return new $6(c7(a.oa,"/bc"),b)},f8=function(a,b){a.U("proxyStateChange",b)},TAa=function(a){a.C=g.vE((0,g.z)(function(){e8("Connecting timeout");
this.D(1)},a),2E4)},g8=function(a){g.xE(a.C);
a.C=window.NaN},h8=function(a){g.xE(a.N);
a.N=window.NaN},UAa=function(a){i8(a);
a.L=g.vE((0,g.z)(function(){j8(this,"getNowPlaying")},a),2E4)},i8=function(a){g.xE(a.L);
a.L=window.NaN},WAa=function(a,b){b&&(g8(a),h8(a));
b==(a7(a.g)&&(0,window.isNaN)(a.C))?b&&(f8(a,1),j8(a,"getSubtitlesTrack")):b?(a.Y()&&a.fb.reset(),f8(a,1),j8(a,"getNowPlaying"),VAa(a)):a.D(1)},XAa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.fb.videoId&&(g.Yb(b.params)?a.fb.o=null:a.fb.o=b.params,a.U("remotePlayerChange"))},YAa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.fb.listId=b.params.listId||a.fb.listId;T7(a.fb,c,d);a.U("remoteQueueChange")},$Aa=function(a,b){b.params=b.params||{};
YAa(a,b);ZAa(a,b);a.U("autoplayDismissed")},ZAa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
R7(a.fb,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.fb.g&&(c=-1E3);a.fb.g=c;c=Number(b.params.loadedTime);a.fb.J=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.fb.I=(0,window.isNaN)(c)?0:c;c=a.fb;var d=Number(b.params.liveIngestionTime);c.B=d;c.D=(0,window.isNaN)(d)?!1:!0;c=a.fb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=(0,window.isNaN)(d)?0:d;c.A=(0,window.isNaN)(e)?0:e;1==a.fb.g?UAa(a):i8(a);
a.U("remotePlayerChange")},aBa=function(a,b){if(-1E3!=a.fb.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.fb.g=c;c=(0,window.parseInt)(b.params.currentTime,10);R7(a.fb,(0,window.isNaN)(c)?0:c);a.U("remotePlayerChange")}},bBa=function(a,b){var c="true"==b.params.muted;
a.fb.volume=(0,window.parseInt)(b.params.volume,10);a.fb.muted=c;a.U("remotePlayerChange")},cBa=function(a,b){a.F=b.params.videoId;
a.U("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},dBa=function(a,b){var c="true"==b.params.hasNext;
a.fb.Kf="true"==b.params.hasPrevious;a.fb.hasNext=c;a.U("previousNextChange")},VAa=function(a){g.xE(a.J);
a.J=g.vE((0,g.z)(a.D,a,1),864E5)},j8=function(a,b,c){c?e8("Sending: action="+b+", params="+g.xg(c)):e8("Sending: action="+b);
a.g.sendMessage(b,c)},k8=function(a){j7.call(this,"ScreenServiceProxy");
this.bd=a;this.o=[];this.o.push(this.bd.$_s("screenChange",(0,g.z)(this.eU,this)));this.o.push(this.bd.$_s("onlineScreenChange",(0,g.z)(this.qQ,this)))},iBa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.OD("MDX_CONFIG")||b;g.SG&&Zya();q6();l8||(l8=new b7(b?b.loungeApiHost:void 0),qza()&&(l8.g="/api/loungedev"));m8||(m8=g.x("yt.mdx.remote.deferredProxies_")||[],g.ua("yt.mdx.remote.deferredProxies_",m8,void 0));eBa();var c=n8();if(!c){var d=new s7(l8);g.ua("yt.mdx.remote.screenService_",d,void 0);c=n8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);JAa(a,d,function(a){a?o8()&&N7(o8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.pG("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.ua("yt.mdx.remote.initialized_",!0,void 0),p8("Initializing: "+g.xg(b)),q8.push(g.lG("yt-remote-cast2-availability-change",function(){g.pG("yt-remote-receiver-availability-change")})),q8.push(g.lG("yt-remote-cast2-receiver-selected",function(){r8(null);
g.pG("yt-remote-auto-connect","cast-selector-receiver")})),q8.push(g.lG("yt-remote-cast2-receiver-resumed",function(){g.pG("yt-remote-receiver-resumed","cast-selector-receiver")})),q8.push(g.lG("yt-remote-cast2-session-change",fBa)),q8.push(g.lG("yt-remote-connection-change",function(a){a?N7(o8(),"YouTube TV"):s8()||(N7(null,null),MAa())})),a=t8(),b.isAuto&&(a.id+="#dial"),g.cF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),p8(" -- with channel params: "+
g.xg(a)),gBa(a),c.start(),o8()||hBa())},kBa=function(){var a=jBa();
K7()&&g.VG("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},jBa=function(){var a=n8().bd.$_gos();
var b=u8();b&&v8()&&(l6(a,b)||a.push(b));return iza(a)},w8=function(){var a=lBa();
!a&&K7()&&LAa()&&(a={key:"cast-selector-receiver",name:LAa()});return a},lBa=function(){var a=jBa(),b=u8();
b||(b=s8());return g.fb(a,function(a){return b&&h6(b,a.key)?!0:!1})},u8=function(){var a=o8();
if(!a)return null;var b=n8().ge();return m6(b,a)},fBa=function(a){p8("remote.onCastSessionChange_: "+i6(a));
if(a){var b=u8();b&&b.id==a.id?N7(b.id,"YouTube TV"):(b&&x8(),y8(a,1))}else v8()&&x8()},x8=function(){L7()?I7().stopSession():G7("stopSession called before API ready.");
var a=v8();a&&(a.disconnect(1),z8(null))},A8=function(){var a=v8();
return!!a&&3!=a.getProxyState()},p8=function(a){f7("remote",a)},n8=function(){if(!B8){var a=g.x("yt.mdx.remote.screenService_");
B8=a?new k8(a):null}return B8},o8=function(){return g.x("yt.mdx.remote.currentScreenId_")},mBa=function(a){g.ua("yt.mdx.remote.currentScreenId_",a,void 0)},nBa=function(){return g.x("yt.mdx.remote.connectData_")},r8=function(a){g.ua("yt.mdx.remote.connectData_",a,void 0)},v8=function(){return g.x("yt.mdx.remote.connection_")},z8=function(a){var b=v8();
r8(null);a||mBa("");g.ua("yt.mdx.remote.connection_",a,void 0);m8&&((0,g.G)(m8,function(b){b(a)}),m8.length=0);
b&&!a?g.pG("yt-remote-connection-change",!1):!b&&a&&g.pG("yt-remote-connection-change",!0)},s8=function(){var a=g.$G();
if(!a)return null;var b=n8().ge();return m6(b,a)},y8=function(a,b){u8()&&u8();
mBa(a.id);var c=new d8(l8,a,t8());c.connect(b,nBa());c.subscribe("beforeDisconnect",function(a){g.pG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){v8()&&z8(null)});
z8(c)},hBa=function(){var a=s8();
a?(p8("Resume connection to: "+i6(a)),y8(a,0)):(r6(),MAa(),p8("Skipping connecting because no session screen found."))},eBa=function(){var a=t8();
if(g.Yb(a)){a=p6();var b=g.VG("yt-remote-session-name")||"",c=g.VG("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.ua("yt.mdx.remote.channelParams_",a,void 0)}},t8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},gBa=function(a){a?(g.UG("yt-remote-session-app",a.app),g.UG("yt-remote-session-name",a.name)):(g.WG("yt-remote-session-app"),g.WG("yt-remote-session-name"));
g.ua("yt.mdx.remote.channelParams_",a,void 0)},C8=function(a,b,c){g.L.call(this);
this.F=a;this.R=b;this.o=new g.WF(this);g.M(this,this.o);this.o.P(b,"onCaptionsTrackListChanged",this.JP);this.o.P(b,"captionschanged",this.qO);this.o.P(b,"captionssettingschanged",this.IC);this.o.P(b,"videoplayerreset",this.Fo);this.o.P(b,"mdxautoplaycancel",this.UG);this.O=this.o.P(b,"onVolumeChange",this.cB);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.pB,this);c.subscribe("remotePlayerChange",this.Gl,this);c.subscribe("remoteQueueChange",this.Fo,this);c.subscribe("autoplayUpNext",this.OA,
this);c.subscribe("previousNextChange",this.mB,this);c.subscribe("nowAutoplaying",this.eB,this);c.subscribe("autoplayDismissed",this.NA,this);this.suggestion=null;this.G=new g.FO(64);this.A=new g.Xt(this.DC,500,this);g.M(this,this.A);this.B=new g.Xt(this.EC,1E3,this);g.M(this,this.B);this.J=new z6(this.ET,0,this);g.M(this,this.J);this.C={};this.L=new g.Xt(this.gD,1E3,this);g.M(this,this.L);this.I=new g.Nk(this.cL,1E3,this);g.M(this,this.I);this.N=g.y;this.IC();this.Fo();this.Gl()},D8=function(a,b){var c=
a.F,d=a.R.ga().lengthSeconds;
c.I=b||0;c.g.U("progresssync",b,d)},oBa=function(a){D8(a,0);
a.A.stop();E8(a,new g.FO(64))},G8=function(a,b){if(F8(a)&&!a.D){var c=null;
b&&(c={style:a.R.yi()},g.ec(c,b));a.g.vC(a.R.ga(1).videoId,c);a.C=X7(a.g).o}},H8=function(a,b){var c=a.R.Uf();
if(c){var d=c.de();var e=c.listId.toString()}var f=a.R.ga(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;f=f.xj;var m=X7(c),n=e||m.listId;l=l||0;var q={videoId:k,currentIndex:l};T7(m,k,l);g.t(b)&&(R7(m,b),q.currentTime=b);g.t(n)&&(q.listId=n);null!=d&&(q.playerParams=d);null!=f&&(q.clickTrackingParams=f);a8(c,"setPlaylist",q);e||Z7(c,m);E8(a,new g.FO(1))},pBa=function(a,b){if(b){var c=a.R.xc("captions","tracklist",{zy:1});
c&&c.length?(a.R.Gd("captions","track",b),a.D=!1):(a.R.vl("captions"),a.D=!0)}else a.R.Gd("captions","track",{})},F8=function(a){return X7(a.g).videoId==a.R.ga(1).videoId},E8=function(a,b){a.B.stop();
var c=a.G;if(!g.LO(c,b)){var d=g.W(b,2);d!=g.W(a.G,2)&&g.LU(a.R,d);a.G=b;qBa(a.F,c,b)}},I8=function(a){g.Y.call(this,{H:"div",
M:"ytp-remote",K:[{H:"div",M:"ytp-remote-display-status",K:[{H:"div",M:"ytp-remote-display-status-icon",K:[g.TD()]},{H:"div",M:"ytp-remote-display-status-text",K:["{{statustext}}"]}]}]});this.o=new g.MV(this,250);g.M(this,this.o);this.A=a;this.P(a,"presentingplayerstatechange",this.B);rBa(this,g.IU(a))},rBa=function(a,b){if(3==a.A.Ra()){var c={RECEIVER_NAME:a.A.xc("remote","currentReceiver").name};
c=g.W(b,128)?g.U("YTP_MDX_STATUS_ERROR_2",c):b.kb()||g.W(b,4)?g.U("YTP_MDX_STATUS_PLAYING_2",c):g.U("YTP_MDX_STATUS_CONNECTED_2",c);a.updateValue("statustext",c);a.o.show()}else a.o.hide()},J8=function(a,b){g.e_.call(this,g.U("YTP_MDX_TITLE"),0,a,b);
this.R=a;this.F={};this.P(a,"onMdxReceiversChange",this.I);this.P(a,"presentingplayerstatechange",this.I);this.I()},K8=function(a){g.EV.call(this,a);
this.A={key:k6(),name:g.U("YTP_MDX_MY_COMPUTER")};this.C=null;this.D=[];this.J=this.o=null;this.G=[this.A];this.B=this.A;this.F=new g.FO(64);this.I=0;if(!g.mM(g.X(this.g))){a=this.g;var b=g.BU(a).G;b&&(b=b.A&&b.A.g)&&(b=new J8(a,b),g.M(this,b));b=new I8(a);g.M(this,b);g.bV(a,b.element,4)}},qBa=function(a,b,c){a.F=c;
a.g.U("presentingplayerstatechange",new g.QO(c,b))},L8=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)x8();
else{a.B=b;var c=a.g.getPlaylistId();var d=a.g.ga(1),e=d.videoId;if(c||e){var f=a.g.Uf();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.gc(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.xj,index:Math.max(a.g.Hz(),0),currentTime:0==f?void 0:f}}else c=null;p8("Connecting to: "+g.xg(b));"cast-selector-receiver"==b.key?(r8(c||null),L7()?I7().setLaunchParams(c||null):G7("setLaunchParams called before ready.")):!c&&
A8()&&o8()==b.key?g.pG("yt-remote-connection-change",!0):(x8(),r8(c||null),c=n8().ge(),(c=m6(c,b.key))&&y8(c,1))}},Hza={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},J6={"'":"\\'"},sBa={},eza={LV:"atp",l0:"ska",B_:"que",OZ:"mus",g0:"sus"};
f6.prototype.fn=function(){var a=new f6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.A=this.A;a.o=this.o;a.g=this.g;return a};
var s6,o6="",yza=t6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",zza=t6("loadCastFramework")||t6("loadCastApplicationFramework"),v6=["boadgeojelhgndaghljhdicfkmllpafd","dliochdbjfkdbacpmhlcpmleaejidimm","enhhojjnijigcajfphajepfemndkmdlo","fmfcbgogabcbclcofgocippekhfcmgfj"],tBa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","fjhoaacokmgbjemoflkofnenfaiekifl"],xza=50<=uza()?tBa.concat(v6):v6.concat(tBa);g.A(z6,g.L);g.h=z6.prototype;g.h.LH=function(a){this.B=arguments;this.g=!1;this.Aa?this.A=(0,g.F)()+this.sc:this.Aa=g.rg(this.C,this.sc)};
g.h.stop=function(){this.Aa&&(g.sg(this.Aa),this.Aa=null);this.A=null;this.g=!1;this.B=[]};
g.h.pause=function(){++this.o};
g.h.resume=function(){this.o&&(--this.o,!this.o&&this.g&&(this.g=!1,this.D.apply(null,this.B)))};
g.h.X=function(){this.stop();z6.aa.X.call(this)};
g.h.MH=function(){this.A?(this.Aa=g.rg(this.C,this.A-(0,g.F)()),this.A=null):(this.Aa=null,this.o?this.g=!0:(this.g=!1,this.D.apply(null,this.B)))};A6.prototype.stringify=function(a){return g.w.JSON.stringify(a,this.g)};
A6.prototype.parse=function(a){return g.w.JSON.parse(a,this.o)};g.h=B6.prototype;g.h.gi=null;g.h.uf=!1;g.h.pk=null;g.h.Eu=null;g.h.Ll=null;g.h.nj=null;g.h.nh=null;g.h.Eh=null;g.h.Hi=null;g.h.Nc=null;g.h.Tl=0;g.h.vf=null;g.h.vp=null;g.h.hi=null;g.h.Vk=-1;g.h.eC=!0;g.h.Qh=!1;g.h.gr=0;g.h.Mo=null;var Fza={},E6={};g.h=B6.prototype;g.h.setTimeout=function(a){this.C=a};
g.h.ES=function(a){a=a.target;var b=this.Mo;b&&3==g.qx(a)?b.lj():this.mD(a)};
g.h.mD=function(a){try{if(a==this.Nc)a:{var b=g.qx(this.Nc),c=this.Nc.o,d=this.Nc.getStatus();if(g.vd&&!g.rc(10)||g.xd&&!g.qc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.$e&&!g.ux(this.Nc))break a;this.Qh||4!=b||7==c||(8==c||0>=d?this.g.qf(3):this.g.qf(2));L6(this);var e=this.Nc.getStatus();this.Vk=e;var f=g.ux(this.Nc);(this.uf=200==e)?(4==b&&H6(this),this.D?(Gza(this,b,f),g.$e&&this.uf&&3==b&&(this.B.V(this.o,"tick",this.vS),this.o.start())):G6(this,f),this.uf&&!this.Qh&&(4==b?this.g.Do(this):
(this.uf=!1,D6(this)))):(this.hi=400==e&&0<f.indexOf("Unknown SID")?3:0,F6(),H6(this),I6(this))}}catch(k){this.Nc&&g.ux(this.Nc)}finally{}};
g.h.vS=function(){var a=g.qx(this.Nc),b=g.ux(this.Nc);this.Tl<b.length&&(L6(this),Gza(this,a,b),this.uf&&4!=a&&D6(this))};
g.h.IR=function(a){K6((0,g.z)(this.HR,this,a),0)};
g.h.HR=function(a){this.Qh||(L6(this),G6(this,a),D6(this))};
g.h.xB=function(a){K6((0,g.z)(this.GR,this,a),0)};
g.h.GR=function(a){this.Qh||(H6(this),this.uf=a,this.g.Do(this),this.g.qf(4))};
g.h.cancel=function(){this.Qh=!0;H6(this)};
g.h.ZR=function(){this.pk=null;var a=(0,g.F)();0<=a-this.Eu?(2!=this.nj&&this.g.qf(3),H6(this),this.hi=2,F6(),I6(this)):Jza(this,this.Eu-a)};g.h=Mza.prototype;g.h.ar=null;g.h.pe=null;g.h.Oo=!1;g.h.Jx=null;g.h.un=null;g.h.dr=null;g.h.fr=null;g.h.Ie=null;g.h.xg=-1;g.h.Uk=null;g.h.tk=null;g.h.connect=function(a){this.fr=a;a=N6(this.g,null,this.fr);F6();this.Jx=(0,g.F)();var b=this.g.I;null!=b?(this.Uk=b[0],(this.tk=b[1])?(this.Ie=1,Nza(this)):(this.Ie=2,P6(this))):(e6(a,"MODE","init"),this.pe=new B6(this,0,void 0,void 0,void 0),this.pe.gi=this.ar,C6(this.pe,a,!1,null,!0),this.Ie=0)};
g.h.VG=function(a){if(a)this.Ie=2,P6(this);else{F6();var b=this.g;b.cf=b.bh.xg;W6(b,9)}a&&this.qf(2)};
g.h.zq=function(a){return this.g.zq(a)};
g.h.abort=function(){this.pe&&(this.pe.cancel(),this.pe=null);this.xg=-1};
g.h.Ix=function(){return!1};
g.h.qB=function(a,b){this.xg=a.Vk;if(0==this.Ie)if(b){try{var c=this.o.parse(b)}catch(d){c=this.g;c.cf=this.xg;W6(c,2);return}this.Uk=c[0];this.tk=c[1]}else c=this.g,c.cf=this.xg,W6(c,2);else if(2==this.Ie)if(this.Oo)F6(),this.dr=(0,g.F)();else if("11111"==b){if(F6(),this.Oo=!0,this.un=(0,g.F)(),c=this.un-this.Jx,!g.vd||g.rc(10)||500>c)this.xg=200,this.pe.cancel(),F6(),O6(this.g,this,!0)}else F6(),this.un=this.dr=(0,g.F)(),this.Oo=!1};
g.h.Do=function(){this.xg=this.pe.Vk;if(this.pe.uf)0==this.Ie?this.tk?(this.Ie=1,Nza(this)):(this.Ie=2,P6(this)):2==this.Ie&&((!g.vd||g.rc(10)?!this.Oo:200>this.dr-this.un)?(F6(),O6(this.g,this,!1)):(F6(),O6(this.g,this,!0)));else{0==this.Ie?F6():2==this.Ie&&F6();var a=this.g;a.cf=this.xg;W6(a,2)}};
g.h.Nl=function(){return this.g.Nl()};
g.h.isActive=function(){return this.g.isActive()};
g.h.qf=function(a){this.g.qf(a)};g.h=Q6.prototype;g.h.Gk=null;g.h.Od=null;g.h.oc=null;g.h.Zq=null;g.h.xn=null;g.h.Yv=null;g.h.Mn=null;g.h.Cl=0;g.h.IN=0;g.h.qd=null;g.h.eh=null;g.h.qg=null;g.h.Uh=null;g.h.bh=null;g.h.up=null;g.h.Bj=-1;g.h.Iy=-1;g.h.cf=-1;g.h.Jk=0;g.h.Xi=0;g.h.Sh=8;var X6=new g.zf;g.A(Pza,g.Ye);g.A(Qza,g.Ye);g.A(Rza,g.Ye);g.h=Q6.prototype;g.h.connect=function(a,b,c,d,e){F6();this.Zq=b;this.Gk=c||{};d&&g.t(e)&&(this.Gk.OSID=d,this.Gk.OAID=e);this.D?(K6((0,g.z)(this.zw,this,a),100),Vza(this)):this.zw(a)};
g.h.zw=function(a){this.bh=new Mza(this);this.bh.ar=null;this.bh.o=this.C;this.bh.connect(a)};
g.h.Ix=function(){return 0==this.g};
g.h.vB=function(a){this.eh=null;Yza(this,a)};
g.h.uB=function(){this.qg=null;this.oc=new B6(this,0,this.A,"rpc",this.F);this.oc.gi=null;this.oc.gr=0;var a=this.Yv.clone();g.zm(a,"RID","rpc");g.zm(a,"SID",this.A);g.zm(a,"CI",this.up?"0":"1");g.zm(a,"AID",this.Bj);R6(this,a);if(!g.vd||g.rc(10))g.zm(a,"TYPE","xmlhttp"),C6(this.oc,a,!0,this.Mn,!1);else{g.zm(a,"TYPE","html");var b=this.oc,c=!!this.Mn;b.nj=3;b.nh=d6(a.clone());Iza(b,c)}};
g.h.qB=function(a,b){if(0!=this.g&&(this.oc==a||this.Od==a))if(this.cf=a.Vk,this.Od==a&&3==this.g)if(7<this.Sh){try{var c=this.C.parse(b)}catch(f){c=null}if(g.xa(c)&&3==c.length)if(0==c[0])a:{if(!this.qg){if(this.oc)if(this.oc.Ll+3E3<this.Od.Ll)T6(this),this.oc.cancel(),this.oc=null;else break a;V6(this);F6()}}else this.Iy=c[1],0<this.Iy-this.Bj&&37500>c[2]&&this.up&&0==this.Xi&&!this.Uh&&(this.Uh=K6((0,g.z)(this.lO,this),6E3));else W6(this,11)}else b!=sBa.OW.g&&W6(this,11);else if(this.oc==a&&T6(this),
!g.C(b)){c=this.C.parse(b);g.xa(c);for(var d=0;d<c.length;d++){var e=c[d];this.Bj=e[0];e=e[1];2==this.g?"c"==e[0]?(this.A=e[1],this.Mn=e[2],e=e[3],null!=e?this.Sh=e:this.Sh=6,this.g=3,this.qd&&this.qd.lw(this),this.Yv=N6(this,this.Nl()?this.Mn:null,this.Zq),Zza(this)):"stop"==e[0]&&W6(this,7):3==this.g&&("stop"==e[0]?W6(this,7):"noop"!=e[0]&&this.qd&&this.qd.kw(this,e),this.Xi=0)}}};
g.h.lO=function(){null!=this.Uh&&(this.Uh=null,this.oc.cancel(),this.oc=null,V6(this),F6())};
g.h.Do=function(a){if(this.oc==a){T6(this);this.oc=null;var b=2}else if(this.Od==a)this.Od=null,b=1;else return;this.cf=a.Vk;if(0!=this.g)if(a.uf)1==b?((0,g.F)(),X6.dispatchEvent(new Qza(X6,a.Hi?a.Hi.length:0)),S6(this),this.B.length=0):Zza(this);else{var c=a.hi,d;if(!(d=3==c||7==c||0==c&&0<this.cf)){if(d=1==b)this.Od||this.eh||1==this.g||2<=this.Jk?d=!1:(this.eh=K6((0,g.z)(this.vB,this,a),$za(this,this.Jk)),this.Jk++,d=!0);d=!(d||2==b&&V6(this))}if(d)switch(c){case 1:W6(this,5);break;case 4:W6(this,
10);break;case 3:W6(this,6);break;case 7:W6(this,12);break;default:W6(this,2)}}};
g.h.sH=function(a){if(!g.kb(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.wT=function(a){a?F6():(F6(),aAa(this,8))};
g.h.zq=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.kx;a.G=!1;return a};
g.h.isActive=function(){return!!this.qd&&this.qd.isActive(this)};
g.h.qf=function(){X6.dispatchEvent(new Rza(X6))};
g.h.Nl=function(){return!(!g.vd||g.rc(10))};
g.h=bAa.prototype;g.h.lw=function(){};
g.h.kw=function(){};
g.h.jw=function(){};
g.h.nq=function(){};
g.h.lx=function(){return{}};
g.h.isActive=function(){return!0};g.A(Z6,g.L);Z6.prototype.A=function(){500<this.sc&&24E4>2*this.sc&&(this.sc*=2);this.B();this.o&&this.start()};
Z6.prototype.start=function(){g.Yt(this.g,this.sc);this.o=(0,g.F)()+this.sc};
Z6.prototype.stop=function(){this.g.stop();this.o=0};
Z6.prototype.isActive=function(){return this.g.isActive()};g.A($6,bAa);g.h=$6.prototype;g.h.subscribe=function(a,b,c){return this.A.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.A.unsubscribe(a,b,c)};
g.h.Id=function(a){return this.A.Id(a)};
g.h.U=function(a,b){return this.A.U.apply(this.A,arguments)};
g.h.dispose=function(){this.J||(this.J=!0,g.We(this.A),eAa(this),g.We(this.o),this.o=null)};
g.h.ka=function(){return this.J};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.I="";this.o.stop();this.C=a||null;this.B=b||0;a=this.L+"/test";b=this.L+"/bind";var d=new Q6("1",c?c.firstTestResults:null,c?c.secondTestResults:null,this.N),e=this.g;e&&(e.qd=null);d.qd=this;this.g=d;e?this.g.connect(a,b,this.D,e.A,e.Bj):c?this.g.connect(a,b,this.D,c.sessionId,c.arrayId):this.g.connect(a,b,this.D)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.ec(c,b);this.o.isActive()||2==(this.g?this.g.g:0)?this.F.push(c):a7(this)&&Wza(this.g,c)};
g.h.lw=function(){Y6(this.o);this.C=null;this.B=0;if(this.F.length){var a=this.F;this.F=[];for(var b=0,c=a.length;b<c;++b)Wza(this.g,a[b])}this.U("handlerOpened")};
g.h.jw=function(a,b){var c=2==b&&401==this.g.cf;if(4!=b&&!c){if(6==b||410==this.g.cf)c=this.o,c.g.stop(),c.sc=500;this.o.start()}this.U("handlerError",b)};
g.h.nq=function(a,b,c){if(!this.o.isActive())this.U("handlerClosed");else if(c)for(a=0,b=c.length;a<b;++a){var d=c[a].map;d&&this.F.push(d)}};
g.h.lx=function(){var a={v:2};this.I&&(a.gsessionid=this.I);0!=this.B&&(a.ui=""+this.B);0!=this.G&&(a.ui=""+this.G);this.C&&g.ec(a,this.C);return a};
g.h.kw=function(a,b){"S"==b[0]?this.I=b[1]:"gracefulReconnect"==b[0]?(Y6(this.o),this.o.start(),Uza(this.g)):this.U("handlerMessage",new cAa(b[0],b[1]))};
g.h.aU=function(){this.o.isActive();var a=this.g,b=0;a.oc&&b++;a.Od&&b++;0!=b?this.o.start():this.connect(this.C,this.B)};b7.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
b7.prototype.A=function(a,b){a(Error("Request error: "+b.status))};
b7.prototype.C=function(a){a(Error("request timed out"))};var mAa=(0,g.F)(),e7=null,h7=Array(50),g7=-1,i7=!1;g.A(j7,g.ZF);j7.prototype.ge=function(){return this.g};
j7.prototype.contains=function(a){return!!l6(this.g,a)};
j7.prototype.get=function(a){return a?m6(this.g,a):null};
j7.prototype.info=function(a){f7(this.F,a)};g.A(k7,g.ZF);var uBa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=k7.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.Aa)&&this.qD()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.Aa)||(g.xE(this.Aa),this.Aa=window.NaN)};
g.h.X=function(){this.stop();k7.aa.X.call(this)};
g.h.qD=function(){this.Aa=window.NaN;this.g=g.LE(c7(this.D,"/pairing/get_screen"),{method:"POST",Pb:{pairing_code:this.C},timeout:5E3,Ib:(0,g.z)(this.cU,this),onError:(0,g.z)(this.bU,this),td:(0,g.z)(this.dU,this)})};
g.h.cU=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.A;c.name=this.B;this.U("pairingComplete",new g6(c))};
g.h.bU=function(a){this.g=null;a.status&&404==a.status?this.o>=uBa.length?this.U("pairingFailed",Error("DIAL polling timed out")):(a=uBa[this.o],this.Aa=g.vE((0,g.z)(this.qD,this),a),this.o++):this.U("pairingFailed",Error("Server error "+a.status))};
g.h.dU=function(){this.g=null;this.U("pairingFailed",Error("Server not responding"))};g.A(m7,j7);g.h=m7.prototype;g.h.start=function(){l7(this)&&this.U("screenChange");!g.VG("yt-remote-lounge-token-expiration")&&qAa(this);g.xE(this.o);this.o=g.vE((0,g.z)(this.start,this),1E4)};
g.h.add=function(a,b){l7(this);nAa(this,a);n7(this,!1);this.U("screenChange");b(a);a.token||qAa(this)};
g.h.remove=function(a,b){var c=l7(this);pAa(this,a)&&(n7(this,!1),c=!0);b(a);c&&this.U("screenChange")};
g.h.qp=function(a,b,c,d){var e=l7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,n7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.U("screenChange")};
g.h.X=function(){g.xE(this.o);m7.aa.X.call(this)};
g.h.YH=function(a){l7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}n7(this,!b);b&&f7(this.F,"Missed "+b+" lounge tokens.")};
g.h.XH=function(a){f7(this.F,"Requesting lounge tokens failed: "+a)};g.A(p7,g.ZF);g.h=p7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.VG("yt-remote-fast-check-period")||"0",10);(this.B=(0,g.F)()-144E5<a?0:a)?r7(this):(this.B=(0,g.F)()+3E5,g.UG("yt-remote-fast-check-period",this.B),this.Ot())};
g.h.isEmpty=function(){return g.Yb(this.g)};
g.h.update=function(){o7("Updating availability on schedule.");var a=this.D(),b=g.Mb(this.g,function(b,d){return b&&!!m6(a,d)},this);
q7(this,b)};
g.h.X=function(){g.xE(this.A);this.A=window.NaN;this.o&&(this.o.abort(),this.o=null);p7.aa.X.call(this)};
g.h.Ot=function(){g.xE(this.A);this.A=window.NaN;this.o&&this.o.abort();var a=tAa(this);if(g.Qb(a)){var b=c7(this.C,"/pairing/get_screen_availability");this.o=d7(this.C,b,{lounge_token:g.Sb(a).join(",")},(0,g.z)(this.hR,this,a),(0,g.z)(this.gR,this))}else q7(this,{}),r7(this)};
g.h.hR=function(a,b){this.o=null;var c=g.Sb(tAa(this));if(g.Fb(c,g.Sb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;q7(this,d);r7(this)}else this.ac("Changing Screen set during request."),this.Ot()};
g.h.gR=function(a){this.ac("Screen availability failed: "+a);this.o=null;r7(this)};
g.h.ac=function(a){f7("OnlineScreenService",a)};g.A(s7,j7);g.h=s7.prototype;g.h.start=function(){this.A.start();this.o.start();this.g.length&&(this.U("screenChange"),this.o.isEmpty()||this.U("onlineScreenChange"))};
g.h.add=function(a,b,c){this.A.add(a,b,c)};
g.h.remove=function(a,b,c){this.A.remove(a,b,c);this.o.update()};
g.h.qp=function(a,b,c,d){this.A.contains(a)?this.A.qp(a,b,c,d):(a="Updating name of unknown screen: "+a.name,f7(this.F,a),d(Error(a)))};
g.h.ge=function(a){return a?this.g:g.ub(this.g,(0,g.Jd)(this.B,function(a){return!this.contains(a)},this))};
g.h.rD=function(){return(0,g.Jd)(this.ge(!0),function(a){return!!this.o.g[a.id]},this)};
g.h.sD=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new k7(this.D,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(a){g.We(f);d(t7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.We(f);e(a)});
f.start();return(0,g.z)(f.stop,f)};
g.h.fU=function(a,b,c,d){g.LE(c7(this.D,"/pairing/get_screen"),{method:"POST",Pb:{pairing_code:a},timeout:5E3,Ib:(0,g.z)(function(a,d){var e=new g6(d.screen||{});if(!e.name||xAa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);xAa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(t7(this,e))},this),
onError:(0,g.z)(function(a){d(Error("pairing request failed: "+a.status))},this),
td:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.h.X=function(){g.We(this.A);g.We(this.o);s7.aa.X.call(this)};
g.h.kI=function(){yAa(this);this.U("screenChange");this.o.update()};
s7.prototype.dispose=s7.prototype.dispose;g.A(v7,g.ZF);g.h=v7.prototype;g.h.Eo=function(a){this.A=a;this.U("sessionScreen",this.A)};
g.h.ne=function(a){this.ka()||(a&&w7(this,""+a),this.A=null,this.U("sessionScreen",null))};
g.h.info=function(a){f7(this.N,a)};
g.h.uD=function(){return null};
g.h.Vt=function(a){var b=this.o;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){w7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.X=function(){this.Vt("");v7.aa.X.call(this)};g.A(x7,v7);g.h=x7.prototype;g.h.Ut=function(a){if(this.g){if(this.g==a)return;w7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.D);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.C)}this.g=a;this.g.addUpdateListener(this.D);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.C);AAa(this)};
g.h.Cj=function(a){this.info("launchWithParams no-op for Cast: "+g.xg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.z)(function(){this.ne()},this),(0,g.z)(function(){this.ne(Error("Failed to stop receiver app."))},this)):this.ne(Error("Stopping cast device witout session."))};
g.h.Vt=g.y;g.h.X=function(){this.info("disposeInternal");g.xE(this.B);this.B=0;this.g&&(this.g.removeUpdateListener(this.D),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.C));this.g=null;x7.aa.X.call(this)};
g.h.jS=function(a,b){if(!this.ka())if(b){var c=g.ex(b);if(c){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.xg(c));switch(d){case "mdxSessionStatus":zAa(this,c.screenId);break;default:w7(this,"Unknown youtube message: "+d)}}else w7(this,"Unable to parse message.")}else w7(this,"No data in message.")};
g.h.Bx=function(a,b,c,d){wAa(this.I,this.o.label,a,this.o.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(w7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.vE((0,g.z)(this.Bx,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.uD=function(){return this.g};
g.h.gU=function(a){this.ka()||a||(w7(this,"Cast session died."),this.ne())};g.A(y7,v7);g.h=y7.prototype;g.h.Ut=function(a){this.B=a;this.B.addUpdateListener(this.L)};
g.h.Cj=function(a){this.C=a;this.F()};
g.h.stop=function(){this.g();this.g=g.y;g.xE(this.D);this.B?this.B.stop((0,g.z)(this.ne,this,null),(0,g.z)(this.ne,this,"Failed to stop DIAL device.")):this.ne()};
g.h.X=function(){this.g();this.g=g.y;g.xE(this.D);this.B&&this.B.removeUpdateListener(this.L);this.B=null;y7.aa.X.call(this)};
g.h.jU=function(a){this.ka()||a||(w7(this,"DIAL session died."),this.g(),this.g=g.y,this.ne())};
g.h.Pr=function(a){this.J=k6();if(this.C){var b=new window.chrome.cast.DialLaunchResponse(!0,CAa(this));a(b);BAa(this)}else this.F=(0,g.z)(function(){g.xE(this.D);this.F=g.y;this.D=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,CAa(this));a(b);BAa(this)},this),this.D=g.vE((0,g.z)(function(){this.F()},this),100)};
g.h.AJ=function(a,b){wAa(this.I,this.G.receiver.label,a,this.o.friendlyName,(0,g.z)(function(a){a&&a.token?(this.Eo(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.Pr(b)},this),(0,g.z)(function(a){w7(this,"Failed to get DIAL screen: "+a);
this.Pr(b)},this))};g.A(z7,v7);z7.prototype.stop=function(){this.ne()};
z7.prototype.Ut=g.y;z7.prototype.Cj=function(){g.xE(this.g);this.g=window.NaN;var a=m6(this.I.ge(),this.o.label);a?this.Eo(a):this.ne(Error("No such screen"))};
z7.prototype.X=function(){g.xE(this.g);this.g=window.NaN;z7.aa.X.call(this)};g.A(A7,g.ZF);g.h=A7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.F);this.G||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.z)(this.rB,this),(0,g.z)(this.SQ,this),d,e);c.customDialLaunchCallback=(0,g.z)(this.WO,this);window.chrome.cast.initialize(c,
(0,g.z)(function(){this.ka()||(window.chrome.cast.addReceiverActionListener(this.B),jAa(),this.o.subscribe("onlineScreenChange",(0,g.z)(this.tD,this)),this.A=EAa(this),window.chrome.cast.setCustomReceivers(this.A,g.y,(0,g.z)(function(a){this.ac("Failed to set initial custom receivers: "+g.xg(a))},this)),this.U("yt-remote-cast2-availability-change",C7(this)),b(!0))},this),(0,g.z)(function(a){this.ac("Failed to initialize API: "+g.xg(a));
b(!1)},this))};
g.h.hT=function(a,b){B7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.A;if(!a||c&&c.id!=a)B7("Unsetting old screen status: "+this.g.o.friendlyName),D7(this,null)}if(a&&b){if(!this.g){c=m6(this.o.ge(),a);if(!c){B7("setConnectedScreenStatus: Unknown screen.");return}var d=DAa(this,c);d||(B7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.A.push(d),
window.chrome.cast.setCustomReceivers(this.A,g.y,(0,g.z)(function(a){this.ac("Failed to set initial custom receivers: "+g.xg(a))},this)));
B7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);D7(this,new z7(this.o,d),!0)}this.g.Vt(b)}else B7("setConnectedScreenStatus: no screen.")};
g.h.iT=function(a){this.ka()?this.ac("Setting connection data on disposed cast v2"):this.g?this.g.Cj(a):this.ac("Setting connection data without a session")};
g.h.iU=function(){this.ka()?this.ac("Stopping session on disposed cast v2"):this.g?(this.g.stop(),D7(this,null)):B7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.z)(this.rB,this),(0,g.z)(this.lR,this))};
g.h.X=function(){this.o.unsubscribe("onlineScreenChange",(0,g.z)(this.tD,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.B);g.sb(g.x("yt.mdx.remote.debug.handlers_")||[],gAa);g.We(this.g);A7.aa.X.call(this)};
g.h.ac=function(a){f7("Controller",a)};
g.h.sB=function(a,b){this.g==a&&(b||D7(this,null),this.U("yt-remote-cast2-session-change",b))};
g.h.OQ=function(a,b){if(!this.ka())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),B7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.o.label!=a.label)B7("onReceiverAction_: Stopping active receiver: "+this.g.o.friendlyName),this.g.stop();else{B7("onReceiverAction_: Casting to active receiver.");this.g.A&&this.U("yt-remote-cast2-session-change",this.g.A);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:D7(this,
new z7(this.o,a));break;case window.chrome.cast.ReceiverType.DIAL:D7(this,new y7(this.o,a,this.D));break;case window.chrome.cast.ReceiverType.CAST:D7(this,new x7(this.o,a));break;default:this.ac("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.o.label==a.label?this.g.stop():this.ac("Stopping receiver w/o session: "+a.friendlyName)}else this.ac("onReceiverAction_ called without receiver.")};
g.h.WO=function(a){if(this.ka())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.ac("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.o:null;if(!c||c.label!=b.label)return this.ac("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.A)return B7("Reselecting dial screen."),
this.U("yt-remote-cast2-session-change",this.g.A),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.ac('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);D7(this,new y7(this.o,b,this.D))}b=this.g;b.G=a;return b.G.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.z)(b.AJ,b,(b.G.extraData||{}).screenId||null)):new window.Promise((0,g.z)(b.Pr,b))};
g.h.rB=function(a){if(!this.ka()){B7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)B7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),D7(this,new x7(this.o,b),!0);else{this.ac("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.o,d=m6(this.o.ge(),c.label);
d&&h6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(B7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.We(this.g),this.g=new x7(this.o,b),this.g.subscribe("sessionScreen",(0,g.z)(this.sB,this,this.g)),this.g.Cj(null));this.g.Ut(a)}}};
g.h.hU=function(){return this.g?this.g.uD():null};
g.h.lR=function(a){this.ka()||(this.ac("Failed to estabilish a session: "+g.xg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&D7(this,null))};
g.h.SQ=function(a){B7("Receiver availability updated: "+a);if(!this.ka()){var b=C7(this);this.C=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;C7(this)!=b&&this.U("yt-remote-cast2-availability-change",C7(this))}};
g.h.tD=function(){this.ka()||(this.A=EAa(this),B7("Updating custom receivers: "+g.xg(this.A)),window.chrome.cast.setCustomReceivers(this.A,g.y,(0,g.z)(function(){this.ac("Failed to set custom receivers.")},this)),this.U("yt-remote-cast2-availability-change",C7(this)))};
A7.prototype.setLaunchParams=A7.prototype.iT;A7.prototype.setConnectedScreenStatus=A7.prototype.hT;A7.prototype.stopSession=A7.prototype.iU;A7.prototype.getCastSession=A7.prototype.hU;A7.prototype.requestSession=A7.prototype.requestSession;A7.prototype.init=A7.prototype.init;A7.prototype.dispose=A7.prototype.dispose;var J7=[];O7.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";P7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.Kf=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.C=a.seekableStart,this.A=a.seekableEnd,this.I=a.duration,this.J=a.loadedTime,this.B=a.liveIngestionTime,this.D=!(0,window.isNaN)(this.B))};
O7.prototype.kb=function(){return 1==this.g};
O7.prototype.getDuration=function(){return this.D?this.I+Q7(this):this.I};
O7.prototype.clone=function(){return new O7(U7(this))};g.A(W7,g.ZF);g.h=W7.prototype;g.h.play=function(){1==this.g?(this.o?this.o.play(null,g.y,c8(this,"play")):a8(this,"play"),$7(this,1,S7(X7(this))),this.U("remotePlayerChange")):Y7(this,this.play)};
g.h.pause=function(){1==this.g?(this.o?this.o.pause(null,g.y,c8(this,"pause")):a8(this,"pause"),$7(this,2,S7(X7(this))),this.U("remotePlayerChange")):Y7(this,this.pause)};
g.h.pD=function(a){if(1==this.g){if(this.o){var b=X7(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.kb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.y,c8(this,"seekTo",{newTime:a}))}else a8(this,"seekTo",{newTime:a});$7(this,3,a);this.U("remotePlayerChange")}else Y7(this,g.Fa(this.pD,a))};
g.h.stop=function(){if(1==this.g){this.o?this.o.stop(null,g.y,c8(this,"stopVideo")):a8(this,"stopVideo");var a=X7(this);a.index=-1;a.videoId="";P7(a);Z7(this,a);this.U("remotePlayerChange")}else Y7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=X7(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.z)(function(){b8("set receiver volume: "+d)},this),(0,g.z)(function(){this.ac("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.z)(function(){b8("set receiver muted: "+b)},this),(0,g.z)(function(){this.ac("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);a8(this,"setVolume",e)}c.muted=b;c.volume=a;Z7(this,c)}else Y7(this,g.Fa(this.setVolume,a,b))};
g.h.vC=function(a,b){if(1==this.g){var c=X7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.xg(b.style),g.ec(d,c.o));a8(this,"setSubtitlesTrack",d);Z7(this,c)}else Y7(this,g.Fa(this.vC,a,b))};
g.h.Ju=function(a,b){if(1==this.g){a8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Rc.id});var c=X7(this);c.audioTrackId=b.Rc.id;Z7(this,c)}else Y7(this,g.Fa(this.Ju,a,b))};
g.h.oD=function(a,b){if(1==this.g){if(a&&b){var c=X7(this);T7(c,a,b);Z7(this,c)}a8(this,"previous")}else Y7(this,g.Fa(this.oD,a,b))};
g.h.nD=function(a,b){if(1==this.g){if(a&&b){var c=X7(this);T7(c,a,b);Z7(this,c)}a8(this,"next")}else Y7(this,g.Fa(this.nD,a,b))};
g.h.Ow=function(){1==this.g?a8(this,"dismissAutoplay"):Y7(this,this.Ow)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.U("proxyStateChange",a,this.g)}W7.aa.dispose.call(this)};
g.h.X=function(){QAa(this);this.B=null;this.C.clear();V7(this,null);W7.aa.X.call(this)};
g.h.Ku=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.U("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)g.lC(this.C).apply(this);else 3==a&&this.dispose()}};
g.h.KQ=function(a,b){this.U(a,b)};
g.h.sO=function(a){if(!a)this.El(null),V7(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=X7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)b8("Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,Z7(this,b)}};
g.h.El=function(a){b8("Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.G);if(this.o=a)this.o.addUpdateListener(this.G),RAa(this),this.U("remotePlayerChange")};
g.h.rO=function(a){a?(RAa(this),this.U("remotePlayerChange")):this.El(null)};
g.h.FO=function(){var a=NAa();a&&V7(this,a)};
g.h.ac=function(a){f7("CP",a)};g.A(d8,g.ZF);g.h=d8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime;g.t(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.t(k)&&(l.currentIndex=k);c&&(this.fb.listId=c);this.fb.videoId=d;this.fb.index=k||0;this.fb.state=3;R7(this.fb,m);this.B="UNSUPPORTED";e8("Connecting with setPlaylist and params: "+g.xg(l));this.g.connect({method:"setPlaylist",params:g.xg(l)},a,lza())}else e8("Connecting without params"),
this.g.connect({},a,lza());TAa(this)};
g.h.dispose=function(){this.ka()||(this.U("beforeDispose"),f8(this,3));d8.aa.dispose.call(this)};
g.h.X=function(){g8(this);i8(this);h8(this);g.xE(this.I);this.I=window.NaN;g.xE(this.J);this.J=window.NaN;this.A=null;g.LF(this.T);this.T.length=0;this.g.dispose();d8.aa.X.call(this);this.B=this.F=this.o=this.fb=this.g=null};
g.h.PH=function(){this.D(2)};
g.h.wO=function(){e8("Channel opened");this.O&&(this.O=!1,h8(this),this.N=g.vE((0,g.z)(function(){e8("Timing out waiting for a screen.");this.D(1)},this),15E3));
pza(dAa(this.g),this.Z)};
g.h.tO=function(){e8("Channel closed");(0,window.isNaN)(this.C)?r6(!0):r6();this.dispose()};
g.h.uO=function(a){r6();(0,window.isNaN)(this.G())?(e8("Channel error: "+a+" without reconnection"),this.dispose()):(this.O=!0,e8("Channel error: "+a+" with reconnection in "+this.G()+" ms"),f8(this,2))};
g.h.vO=function(a){a.params?e8("Received: action="+a.action+", params="+g.xg(a.params)):e8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.ex(a.params.devices);this.o=(0,g.H)(a,function(a){return new f6(a)});
a=!!g.fb(this.o,function(a){return"LOUNGE_SCREEN"==a.type});
WAa(this,a);break;case "loungeScreenDisconnected":g.tb(this.o,function(a){return"LOUNGE_SCREEN"==a.type});
WAa(this,!1);break;case "remoteConnected":var b=new f6(g.ex(a.params.device));g.fb(this.o,function(a){return b?a.id==b.id:!1})||g.qb(this.o,b);
break;case "remoteDisconnected":b=new f6(g.ex(a.params.device));g.tb(this.o,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":YAa(this,a);break;case "nowPlaying":$Aa(this,a);break;case "onStateChange":ZAa(this,a);break;case "onAdStateChange":aBa(this,a);break;case "onVolumeChanged":bBa(this,a);break;case "onSubtitlesTrackChanged":XAa(this,a);break;case "nowAutoplaying":cBa(this,a);break;case "autoplayDismissed":this.U("autoplayDismissed");break;case "autoplayUpNext":this.F=a.params.videoId||null;this.U("autoplayUpNext",this.F);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.U("autoplayModeChange",this.B);"DISABLED"==this.B&&this.U("autoplayDismissed");break;case "onHasPreviousNextChanged":dBa(this,a);break;case "requestAssistedSignIn":this.U("assistedSignInRequested",a.params.authCode);break;default:e8("Unrecognized action: "+a.action)}};
g.h.SS=function(){if(this.A){var a=this.A;this.A=null;this.fb.videoId!=a&&j8(this,"getNowPlaying")}};
d8.prototype.subscribe=d8.prototype.subscribe;d8.prototype.unsubscribeByKey=d8.prototype.Id;d8.prototype.fa=function(){var a=3;this.ka()||(a=0,(0,window.isNaN)(this.G())?a7(this.g)&&(0,window.isNaN)(this.C)&&(a=1):a=2);return a};
d8.prototype.getProxyState=d8.prototype.fa;d8.prototype.D=function(a){e8("Disconnecting with "+a);g8(this);this.U("beforeDisconnect",a);1==a&&r6();eAa(this.g,a);this.dispose()};
d8.prototype.disconnect=d8.prototype.D;d8.prototype.ea=function(){var a=this.fb;this.A&&(a=this.fb.clone(),T7(a,this.A,a.index));return U7(a)};
d8.prototype.getPlayerContextData=d8.prototype.ea;
d8.prototype.na=function(a){var b=new O7(a);b.videoId&&b.videoId!=this.fb.videoId&&(this.A=b.videoId,g.xE(this.I),this.I=g.vE((0,g.z)(this.SS,this),5E3));var c=[];this.fb.listId==b.listId&&this.fb.videoId==b.videoId&&this.fb.index==b.index||c.push("remoteQueueChange");this.fb.g==b.g&&this.fb.volume==b.volume&&this.fb.muted==b.muted&&S7(this.fb)==S7(b)&&g.xg(this.fb.o)==g.xg(b.o)||c.push("remotePlayerChange");this.fb.reset(a);(0,g.G)(c,function(a){this.U(a)},this)};
d8.prototype.setPlayerContextData=d8.prototype.na;d8.prototype.Y=function(){var a=this.g.D.id,b=g.fb(this.o,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
d8.prototype.getOtherConnectedRemoteId=d8.prototype.Y;d8.prototype.G=function(){var a=this.g;return a.o.isActive()?a.o.o-(0,g.F)():window.NaN};
d8.prototype.getReconnectTimeout=d8.prototype.G;d8.prototype.ba=function(){return this.B||"UNSUPPORTED"};
d8.prototype.getAutoplayMode=d8.prototype.ba;d8.prototype.da=function(){return this.F||""};
d8.prototype.getAutoplayVideoId=d8.prototype.da;d8.prototype.ra=function(){if(!(0,window.isNaN)(this.G())){var a=this.g.o;g.Zt(a.g);a.start()}};
d8.prototype.reconnect=d8.prototype.ra;d8.prototype.ha=function(a,b){j8(this,a,b);VAa(this)};
d8.prototype.sendMessage=d8.prototype.ha;g.A(k8,j7);g.h=k8.prototype;g.h.ge=function(a){return this.bd.$_gs(a)};
g.h.contains=function(a){return!!this.bd.$_c(a)};
g.h.get=function(a){return this.bd.$_g(a)};
g.h.start=function(){this.bd.$_st()};
g.h.add=function(a,b,c){this.bd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.bd.$_r(a,b,c)};
g.h.qp=function(a,b,c,d){this.bd.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.o.length;a<b;++a)this.bd.$_ubk(this.o[a]);this.o.length=0;this.bd=null;k8.aa.X.call(this)};
g.h.eU=function(){this.U("screenChange")};
g.h.qQ=function(){this.U("onlineScreenChange")};
s7.prototype.$_st=s7.prototype.start;s7.prototype.$_gspc=s7.prototype.fU;s7.prototype.$_gsppc=s7.prototype.sD;s7.prototype.$_c=s7.prototype.contains;s7.prototype.$_g=s7.prototype.get;s7.prototype.$_a=s7.prototype.add;s7.prototype.$_un=s7.prototype.qp;s7.prototype.$_r=s7.prototype.remove;s7.prototype.$_gs=s7.prototype.ge;s7.prototype.$_gos=s7.prototype.rD;s7.prototype.$_s=s7.prototype.subscribe;s7.prototype.$_ubk=s7.prototype.Id;var l8=null,m8=null,B8=null,q8=[];g.p(C8,g.L);g.h=C8.prototype;
g.h.X=function(){g.L.prototype.X.call(this);this.A.stop();this.B.stop();this.J.stop();this.N();this.g.unsubscribe("proxyStateChange",this.pB,this);this.g.unsubscribe("remotePlayerChange",this.Gl,this);this.g.unsubscribe("remoteQueueChange",this.Fo,this);this.g.unsubscribe("autoplayUpNext",this.OA,this);this.g.unsubscribe("previousNextChange",this.mB,this);this.g.unsubscribe("nowAutoplaying",this.eB,this);this.g.unsubscribe("autoplayDismissed",this.NA,this);this.g=this.F=null};
g.h.yz=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(F8(this)){if(1081!=X7(this.g).g||"control_seek"!=a)switch(a){case "control_toggle_play_pause":X7(this.g).kb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.lj(c[0],c[1]);break;case "control_subtitles_set_track":G8(this,c[0]);break;case "control_set_audio_track":c=c[0],F8(this)&&this.g.Ju(this.R.ga(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.R.getCurrentTime();H8(this,0==c?void 0:c);break;case "control_seek":H8(this,c[0]);break;case "control_subtitles_set_track":G8(this,c[0]);break;case "control_set_audio_track":c=c[0],F8(this)&&this.g.Ju(this.R.ga(1).videoId,c)}};
g.h.qO=function(a){this.J.LH(a)};
g.h.ET=function(a){this.yz("control_subtitles_set_track",g.Yb(a)?null:a)};
g.h.IC=function(){var a=this.R.xc("captions","track");g.Yb(a)||G8(this,a)};
g.h.cB=function(a){if(F8(this)){this.g.unsubscribe("remotePlayerChange",this.Gl,this);var b=Math.round(a.volume);a=!!a.muted;var c=X7(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.L.start();this.g.subscribe("remotePlayerChange",this.Gl,this)}};
g.h.JP=function(){g.Yb(this.C)||pBa(this,this.C);this.D=!1};
g.h.pB=function(a,b){this.B.stop();2==b&&this.EC()};
g.h.Gl=function(){if(F8(this)){this.A.stop();var a=X7(this.g);switch(a.g){case 1081:case 1:E8(this,new g.FO(8));this.DC();break;case 1085:case 3:E8(this,new g.FO(9));break;case 1083:case 0:E8(this,new g.FO(2));this.I.stop();D8(this,this.R.ga().lengthSeconds);break;case 1084:E8(this,new g.FO(4));break;case 2:E8(this,new g.FO(4));D8(this,S7(a));break;case -1:E8(this,new g.FO(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.U("YTP_MDX_PLAYER_ERROR")},E8(this,new g.FO(128,a))}a=X7(this.g).o;
var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,pBa(this,a));a=X7(this.g);-1==a.volume||Math.round(this.R.getVolume())==a.volume&&this.R.isMuted()==a.muted||this.L.isActive()||this.gD()}else oBa(this)};
g.h.mB=function(){this.R.U("mdxpreviousnextchange")};
g.h.Fo=function(){F8(this)||oBa(this)};
g.h.UG=function(){this.g.Ow()};
g.h.OA=function(a){a&&(a=g.LE("/watch_queue_ajax",{method:"GET",Yc:{action_get_watch_queue_item:1,video_id:a},Ib:(0,g.z)(this.LR,this)}))&&(this.N=(0,g.z)(a.abort,a))};
g.h.LR=function(a,b){var c=new g.HN({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.R.U("mdxautoplayupnext",c)};
g.h.eB=function(a){(0,window.isNaN)(a)||this.R.U("mdxnowautoplaying",a)};
g.h.NA=function(){this.R.U("mdxautoplaycanceled")};
g.h.cL=function(a,b){-1==X7(this.g).g?H8(this,a):b&&this.g.pD(a)};
g.h.gD=function(){if(F8(this)){var a=X7(this.g);this.o.Ea(this.O);a.muted?this.R.mute():this.R.Vf();this.R.setVolume(a.volume);this.O=this.o.P(this.R,"onVolumeChange",this.cB)}};
g.h.DC=function(){this.A.stop();if(!this.g.ka()){var a=X7(this.g);a.kb()&&E8(this,new g.FO(8));D8(this,S7(a));this.A.start()}};
g.h.EC=function(){this.B.stop();this.A.stop();var a=this.g.B.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.p(I8,g.Y);I8.prototype.B=function(a){rBa(this,a.state)};g.p(J8,g.e_);J8.prototype.I=function(){var a=this.R.xc("remote","receivers");a&&1<a.length&&!this.R.xc("remote","quickCast")?(this.F=g.Hb(a,this.B,this),g.f_(this,(0,g.H)(a,this.B)),a=this.R.xc("remote","currentReceiver"),this.pf(this.B(a)),this.enable(!0)):this.enable(!1)};
J8.prototype.B=function(a){return a.key};
J8.prototype.nf=function(a){return"cast-selector-receiver"==a?g.U("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
J8.prototype.sd=function(a){g.e_.prototype.sd.call(this,a);this.R.Gd("remote","currentReceiver",this.F[a]);this.A.Nb()};g.p(K8,g.EV);g.h=K8.prototype;g.h.create=function(){iBa(g.aM(g.X(this.g)));this.D.push(g.lG("yt-remote-before-disconnect",this.mO,this));this.D.push(g.lG("yt-remote-connection-change",this.TQ,this));this.D.push(g.lG("yt-remote-receiver-availability-change",this.nB,this));this.D.push(g.lG("yt-remote-auto-connect",this.RQ,this));this.D.push(g.lG("yt-remote-receiver-resumed",this.QQ,this));this.nB()};
g.h.load=function(){this.g.Ms();g.EV.prototype.load.call(this);this.C=new C8(this,this.g,this.o);var a=(a=nBa())?a.currentTime:0;var b=A8()?new W7(v8(),void 0):null;0==a&&b&&(a=S7(X7(b)));0!=a&&(this.I=a||0,this.g.U("progresssync",a,void 0));qBa(this,this.F,this.F);g.$_(this.g.app,6)};
g.h.unload=function(){this.g.U("mdxautoplaycanceled");this.B=this.A;g.Xe(this.C,this.o);this.o=this.C=null;g.EV.prototype.unload.call(this);g.$_(this.g.app,5)};
g.h.X=function(){g.mG(this.D);g.EV.prototype.X.call(this)};
g.h.pl=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.yz.apply(this.C,[].concat([a],g.pa(c)))};
g.h.HH=function(){return this.loaded?this.C.suggestion:null};
g.h.Kf=function(){return this.o?X7(this.o).Kf:!1};
g.h.hasNext=function(){return this.o?X7(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.I};
g.h.FK=function(){var a=X7(this.o),b=this.g.ga();return{allowSeeking:this.g.cd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.D?a.B+Q7(a):a.B,isPeggedToLive:1>=(a.D?a.A+Q7(a):a.A)-this.getCurrentTime(),loaded:a.J,seekableEnd:a.D?a.A+Q7(a):a.A,seekableStart:0<a.C?a.C+Q7(a):a.C}};
g.h.GK=function(){this.o&&this.o.nD()};
g.h.HK=function(){this.o&&this.o.oD()};
g.h.mO=function(a){1==a&&(this.J=this.o?X7(this.o):null)};
g.h.TQ=function(){var a=A8()?new W7(v8(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.J=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.We(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.J)&&a.videoId==this.g.ga().videoId&&this.g.Fz(a.videoId,S7(a)));this.g.U("videodatachange","newdata",this.g.ga(),3)};
g.h.nB=function(){this.G=[this.A].concat(kBa());var a=w8()||this.A;L8(this,a);this.g.va("onMdxReceiversChange")};
g.h.RQ=function(){var a=w8();L8(this,a)};
g.h.QQ=function(){this.B=w8()};
g.h.EK=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?M7():L8(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&M7(),!0):!1}};
g.h.IK=function(){a8(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.ud=function(){return!1};g.hY.remote=K8;})(_yt_player);
